CREATE TABLE IF NOT EXISTS wp_lgpd_responses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_ip VARCHAR(100) NOT NULL,
    user_agent TEXT NOT NULL,
    response VARCHAR(10) NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
